export const drunkCorrections: { [key: string]: string } = {
    "drnuk": "drunk",
    "whaaaat": "what",
    "gonnaaa": "gonna",
    "hime": "home",
    "dfrunk": "drunk",
    "imfinee": "I'm fine",
    "shhould": "should",
    "plsss": "please",
    "immm": "I'm",
    "heyy": "hey",
    "nighr": "night",
    "imma": "I'm going to",
    "gunna": "gonna",
    "gonnna": "gonna",
    "definately": "definitely",
    "imdrunk": "I'm drunk",
    "wherre": "where",
    "wnat": "want",
    "alrigjt": "alright",
    "helllo": "hello",
    "okkk": "okay",
    "nite": "night",
    "nighht": "night",
    "loove": "love",
    "baaaaby": "baby",
    "wuts": "what's",
    "u": "you",
    "r": "are",
    "wat": "what",
    "cuz": "because"
  };